flowchart TD
  User["User"]

  subgraph "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Local Endpoint"
    Browser["Browser"]
    Extension["Citadel Extension"]
    Agent["Citadel Agent"]
    Logs["Syslog / Event Log"]
    EDR["EDR / XDR"]
  end

  SIEM["SIEM"]
  SOC["SOC<br/>(Security Operations Center)"]

  User --> Browser
  Browser --> Extension
  Extension -- "captures browser events<br/>sends security events to agent" --> Agent
  Agent -- "captures device state<br/>sends to extension for analysis" --> Extension
  Agent -- "sends security events from extension<br/>& device state events to logs" --> Logs
  Logs -- "system and security events" --> EDR
  EDR -- "ships logs" --> SIEM
  SIEM -- "security alerts, events, reports" --> SOC